apiVersion: v1
description: "Kubernetes resources for CFS Hardware Sync Agent"
name: "cfs-hwsync-agent"
home: "scms/cfs-hwsync-agent"
version: 1.3.4
keywords:
  - cfs
  - cfs-hwsync-agent
sources:
  - "https://stash.us.cray.com/projects/SCMS/repos/cfs-hwsync-agent/browse"
