# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

hwsync_image:
  repository: cray/cfs-hwsync-agent
  version: latest

cray-service:
  type: Deployment
  nameOverride: cfs-hwsync-agent
  serviceAccountName: cfs-hwsync-agent
  labels:
    app: cfs-hwsync-agent
  replicaCount: 1
  containers:
    cfs-hwsync-agent:
      name: cfs-hwsync-agent
      image:
        repository: cray/cfs-hwsync-agent
        pullPolicy: Always
      livenessProbe:
        exec:
          command:
          - python3
          - "-m"
          - "hwsyncagent.liveness"
        initialDelaySeconds: 10
        periodSeconds: 30
  service:
    enabled: false
