#
# MIT License
#
# (C) Copyright 2021-2022, 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

hwsync_image:
  repository: artifactory.algol60.net/csm-docker/S-T-A-B-L-E/cfs-hwsync-agent
  version: 0.0.0-image

cray-service:
  type: Deployment
  nameOverride: cfs-hwsync-agent
  serviceAccountName: cfs-hwsync-agent
  labels:
    app: cfs-hwsync-agent
  replicaCount: 1
  containers:
    cfs-hwsync-agent:
      name: cfs-hwsync-agent
      image:
        repository: artifactory.algol60.net/csm-docker/S-T-A-B-L-E/cfs-hwsync-agent
      livenessProbe:
        exec:
          command:
          - python3
          - "-m"
          - "hwsyncagent.liveness"
        initialDelaySeconds: 10
        periodSeconds: 30
  service:
    enabled: false
